Name: "gd-random"
Image: "harbor.smoa.cc/fayez/cuda121conda:runtime"
Command: "source ~/.bashrc; conda activate DIR; cd ~/test/DIR/main; export 
  PYTHONPATH=. ; python train.py --cfg-file gd-train.yml"
GPU: 6                          # optional
Debug: false                     # optional 
Excludes:
  - node01
  - node02
arch: ampere
